create table STUDENTS(
ID int not null,
NAME varchar(25) not null,
AGE int
);
alter table STUDENTS
  add CITY varchar(20),
  add CONTACT varchar(10);
alter table STUDENTS add GENDER varchar(10) after AGE;
select * from STUDENTS;


INSERT INTO STUDENTS VALUES
(1,'SURESH',28,'MALE','HOSUR','2400048352'),
(2,'HARI',11,'MALE','VELUR','2456896352'),
(3,'DIVYA',19,'FEMALE','SALEM','0006896352'),
(4,'RAVI',20,'MALE','COIMBATORE','2456895555'),
(5,'DEVI',24,'FEMALE','HOSUR','2450000052');
INSERT INTO STUDENTS VALUES(6,'MANI',22,'MALE','VELUR','5896478596'),
(7,'HARSATH',38,'MALE','HOSUR','2400048352'),
(8,'SURIYA',13,'MALE','KARUR','2456896352'),
(9,'SARANYA',18,'FEMALE','SALEM','0006896352'),
(10,'SAMY',21,'MALE','COIMBATORE','2456895555');
SELECT * FROM STUDENTS;
SELECT distinct ID FROM STUDENTS;

SELECT NAME,AGE FROM STUDENTS;

SELECT NAME,AGE FROM STUDENTS WHERE CITY='HOSUR' AND AGE>=22;

SELECT NAME,AGE FROM STUDENTS WHERE GENDER='MALE' OR CITY='KARUR';

SELECT NAME,AGE,GENDER,CITY FROM STUDENTS WHERE (GENDER='MALE' OR CITY='KARUR') AND AGE>=20;

SELECT COUNT(CITY) FROM STUDENTS;
SELECT COUNT(CITY) AS TOTAL FROM STUDENTS;

SELECT max(AGE) FROM STUDENTS;
SELECT min(AGE) FROM STUDENTS;
SELECT avg(AGE) FROM STUDENTS;
SELECT round(AVG (AGE),0) FROM STUDENTS;

SELECT GENDER,COUNT(ID) FROM STUDENTS GROUP BY GENDER;
SELECT CITY,COUNT(ID) AS TOTAL FROM STUDENTS GROUP BY CITY;

SELECT NAME FROM STUDENTS WHERE NAME LIKE '%A%';
SELECT NAME FROM STUDENTS WHERE NAME LIKE '%A';

CREATE INDEX INX_STUDENTS ON STUDENTS(ID);


